baseURL = '/'
title = 'Pure Data'

disableKinds = ["taxonomy", "taxonomyTerm"]


defaultContentLanguage = "en"
defaultContentLanguageInSubdir = 'false'


[languages]
  [languages.en]
    contentDir = 'content/english'
    languageName = 'English'
    weight = 10
  [languages.es]
    contentDir = 'content/spanish'
    languageName = 'Español'
    weight = 20
  [languages.fr]
    contentDir = 'content/french'
    languageName = 'Français'
    weight = 30
  [languages.de]
    contentDir = 'content/german'
    languageName = 'Deutsch'
    weight = 40
