baseURL = "/"
languageCode = "en"
title = "Pure Data"
description = "Pd Portal"
theme = "kube"


[Params]
  author = "IOhannes m zmölnig" # add your company name
  email = "noc@iem.at"

#[[menu.main]]
#    name = "Documentation"
#    weight = -100
#    url = "/docs/"
#
#[[menu.main]]
#    name = "FAQ"
#    weight = -80
#    url = "/faq/"
#
#[[menu.main]]
#    name = "Tags"
#    weight = 1
#    url = "/categories/"

[taxonomies]
  category = "categories"

[related]
  includeNewer = false
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "categories"
    weight = 100
